// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let fibArr = [1,2]

// generates a Fibonacci sequence. Takes in two arguments: how many elements in the array you want, and a maximum number any element cannot exceed
const fibSeqGen = (fibTerm, maxNum) => {
  let nextElement = 0

  for (var i = 0; i < (fibTerm - 2); i++) {
    nextElement = fibArr[i] + fibArr[i+1]
    if (nextElement < maxNum) {
      fibArr.push(nextElement)
    } else {
      break
    }
  }

  console.log(fibArr);
}

// takes in an array and sums only the even numbers. Outputs a number.
const sumEven = (inputArr) => {
  let sum = 0
  for (var i = 0; i < inputArr.length; i++) {
    if (inputArr[i] % 2 === 0) {
      console.log(`Even number found: ${inputArr[i]}.`);
      sum += inputArr[i]
    }
  }
  console.log(sum);
}

fibSeqGen(120,4000000)
sumEven(fibArr)
